name: ci
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
        name: Checkout
      - uses: cachix/install-nix-action@v17
        name: Install Nix
        with:
          nix_path: nixpkgs=./nix/pkgs.nix
      - uses: cachix/cachix-action@v10
        name: Set up Cachix
        with:
          name: awakesecurity
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-build
        name: nix-build

  build-macos:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v3.0.2
        name: Checkout
      - uses: cachix/install-nix-action@v17
        name: Install Nix
        with:
          nix_path: nixpkgs=./nix/pkgs.nix
      - uses: cachix/cachix-action@v10
        name: Set up Cachix
        with:
          name: awakesecurity
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-build
        name: nix-build
